version: '3.8'
services:
  auth-service:
    image: astar5327/auth-service
    container_name: auth-service
    ports:
      - "0:8080"
    environment:
        - SPRING_PROFILES_ACTIVE=prod
        - MYSQL_USER=root
        - MYSQL_PASSWORD=1234
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-auth:3306/auth
    networks:
      - msa-network
    depends_on:
      mysql-auth:
        condition: service_healthy
      garnet:
        condition: service_started
  mysql-auth:
    image: mysql:8.4
    container_name: mysql-auth
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: auth
    networks:
      - msa-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
  garnet:
    image: ghcr.io/microsoft/garnet:latest
    container_name: garnet
    ports:
      - "6379:6379"
    networks:
      - msa-network


volumes:
  mysql-auth:

networks:
  msa-network:
    external: true