version: '3.8'
services:
  auth-service:
    image: astar5327/auth-service
    container_name: auth-service
    ports:
      - "0:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - msa-network
networks:
  msa-network:
    external: true
