version: '3.8'
services:
  auth-service:
    image: astar5327/auth-service
    container_name: auth-service
    ports:
      - "0:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/auth
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka-1:9092,kafka-2:9092,kafka-3:9092
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - SPRING_DATA_REDIS_HOST=garnet
      - SPRING_DATA_REDIS_PORT=6379
    networks:
      - msa-network
networks:
  msa-network:
    external: true
