version: '3.8'
services:
  auth-service:
    image: astar5327/auth-service
    container_name: auth-service
    ports:
      - "0:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_USER=root
      - MYSQL_PASSWORD=1234
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/auth
    networks:
      - msa-network
networks:
  msa-network:
    external: true