spring:
  application:
    name: auth-service
  mail:
    password: ${MAIL_PASSWORD}
    username: ${MAIL_USERNAME}
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 0 # random port for security reasons
  shutdown: graceful
