name: CI/CD
on:
  push:
    branches: [ "main" ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build -x test -Pspring.profiles.active=prod

      - name: Docker build and push
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/auth-service . 
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/auth-service

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo docker rm -f product-service || true
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/auth-service
            mkdir /home/ubuntu/auth-service
            cd ~/auth-service
            echo "SPRING_PROFILES_ACTIVE=prod" > .env
            echo ${{ secrets.docker_compose }} > docker-compose.yml
            sudo docker-compose up -d
            sudo docker image prune -f